#!/bin/sh
export CODEBASE=http://$HOSTNAME:\${port}/computefarm-0.8.2.jar
java  -Djava.util.logging.config.file=logging.properties \
  -Djava.security.manager= \
  -Djava.security.policy=policy.all \
  -Dorg.tiling.computefarm.rmi.server.codebase.template=$CODEBASE \
  -jar computefarm-0.8.2.jar
