package org.tiling.computefarm;

/**
 * A {@link Job} is a piece of work generated by
 * a client of the computefarm, which the client gets the computefarm to run using a
 * {@link JobRunner}. A <code>Job</code> is split into {@link Task} objects by the client.
 */
public interface Job {
	/**
	 * When this method is invoked by the framework, the implementation
	 * of <code>Job</code> should create instances of {@link Task}
	 * and write them to the supplied {@link ComputeSpace}.
	 * @param computeSpace
	 */
	public void generateTasks(ComputeSpace computeSpace);
	
	/**
	 * When this method is invoked by the framework, the implementation
	 * of <code>Job</code> should take result Object instances
	 * from the supplied {@link ComputeSpace} and then re-assemble them into a final result.
	 * @param computeSpace
	 */	
	public void collectResults(ComputeSpace computeSpace);
}